# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  licenser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Download licenser
      run: 'wget -c https://github.com/liamawhite/licenser/releases/download/v0.6.0/licenser_0.6.0_Linux_x86_64.tar.gz -O - | sudo tar -xz -C /usr/bin'
    - name: Verify licenses
      run: licenser verify -r
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        TF_ACC: 1
      run: go test -v ./...
